### PR TITLE
Add form control

### LINKED ISSUE #35: [Form Control] Create form control wrapper

### PR DESCRIPTION
**Pull request by ileaugustin**
closes #35

### CODE REVIEW

**Comment by adrianoresende** [comment]
I noticed that the style is different with Chakra:

The border changed.

## Rock UI Input
image
## Chakra Input
image

____

It seems that this changed the `Menu` too, is not a token that has been modified?

## Rock UI Menu
image
## Chakra UI Menu
image

**Comment by adrianoresende** [comment]
I think it is because of CSS global.

Need this style:
https://github.com/chakra-ui/chakra-ui/blob/master/packages/theme/src/styles/index.ts

image

**Comment by hugodias** [comment]
@adrianoresende could you use Chromatic interface to add the UX/UI reviews? 

You can click on Review > Deny for a specific component

image

**Comment by ileaugustin** [comment]
@adrianoresende this issue should be fixed now.
@maracaipe I've replaced the ThemeProvider with the ChakraProvider, in preview.tsx for the stories.

**Comment by adrianoresende** [comment]
PR approved for me 👍

**Pull request merged**
