### PR TITLE
Add Heading component

### PR DESCRIPTION
**Pull request by lucasinoue**
Added a Heading component based on Chakra-UI, using Manrope font.

### CODE REVIEW

**Comment by maracaipe** [comment]
Hi! Thanks for your first PR. It's strange why the GH action did not run 🤔

**Review by maracaipe — APPROVED** [review]
Looks good to me

**Comment by maracaipe** [comment]
@lucasinoue could you please update your PR based on this repo's master branch?

**Comment by lucasinoue** [comment]
What Should I do with chromatic error: ✖ Missing project token?

**Comment by maracaipe** [comment]
Closing due to actions issue.

**Pull request closed without merging**
